name: Add new data points daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Append to csv
        run: go run append.go

      - name: Set git config
        run: |
          git config --global user.email "l7mp.info@gmail.com"
          git config --global user.name "BotL7mp"

      - name: Commit changes
        run: |
          DATE=`date -I`
          git add *.csv
          git commit -m "Add new data points at $DATE"
          git push origin main
